name: cicd for hts

on:
  push:
    branches: ["main"]  # fixed from 'branch'

jobs:  # was 'job' before
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0  # fixed: was a description instead of actual action
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling latest image from Docker Hub..."
            docker pull murtaza007/hts-image:latest

            echo "Stopping and removing old container..."
            docker stop hts-container || true
            docker rm hts-container || true

            echo "Running new container..."
            docker run -d -p 80:80 --name hts-container murtaza007/hts-image:latest

            echo "✅ Deployment successful"